# Generated by Django 5.1.3 on 2024-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classnest_Base", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="links",
            field=models.URLField(blank=True),
        ),
    ]
