# Generated by Django 5.1.3 on 2024-11-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classnest_Base", "0003_profile_bio_profile_contact_profile_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="links",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
    ]
